[project]
name = "dspy-intro"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dspy>=3.0.4b1",
    "matplotlib>=3.10.7",
    "polars>=1.34.0",
    "python-dotenv>=1.1.1",
]
